### ISSUE TITLE
🟥 浸水した能登病院さんに中抜きのない寄付をしたい！方法がないので自作しよう！We build commission free donation system for hospital in Noto

### ISSUE THREAD

**Issue by daijapan** [daijapan/noto-thon-npo#1]

**Comment by daijapan** [comment]
@Hisato-Kiara  状況の軽い説明とStripeのUX不十分な点を述べてくださいませ

**Comment by Hisato-Kiara** [comment]
As is: 
1. 既存のファンディングサイトの中抜きって必要なんだろうか
2. 募金なのか詐欺なのかわからないのがおおい

**Comment by daijapan** [comment]
@Hisato-Kiara  一番欲しい意見は、もうあるやんか！アホちゃう、という情報です。車輪の再発明だけはしたくない。あるなら使う。ないなら作る。

**Comment by Hisato-Kiara** [comment]
Stripe v1.0へのコメント
1. なんかstripeの変な認証が出たので、私(stripeのアカウント持ってる)とstripeのアカウント持ってない人でUX違うかも
2. 画面が味気なくて募金感がない
<img width="1074" alt="スクリーンショット 2024-01-03 14 56 18" src="https://github.com/daijapan/noto-thon-npo/assets/153629977/36828181-22a0-4de8-a8ea-d4ef2d491309">

**Comment by daijapan** [comment]
誠に有難うございます。あるけどちょっと違うのつくりたい、は今回やめましょうね。非論理的なので。それは暇な時のロジックなので。

**Comment by daijapan** [comment]
しばらくアイデアを熟成させよう。誰かが始めたらそれに乗っかればいいし

**Comment by Hisato-Kiara** [comment]
私の寄付した1000円、ちゃんと能登総合病院に寄付されるんだろうか、、、

**Comment by daijapan** [comment]
@Hisato-Kiara  これ、どんなに一生懸命作っても怪しく見えないですかね？
解けない問題にチャレンジしていると思いますが、いかがでしょうか？
逆に言えば、ready for / go fund me / 等々の一般的なプラットフォームにadd-on marketplace欲しいですね
カスタマイズできるように。そういうのないかな。brand powerって一朝一夕には作れないですね。
信頼されているものに小判鮫的な開発をして、資金の行き先の証明書をつくる。
一方、そこはTECH必須かどうかも考える必要ある

**Comment by daijapan** [comment]
ああ、あと、実際に中抜きされてめちゃくちゃ腹たった経験がないなあ。
逆に、もし病院が腹立ってるんだったら教えてください。
そいういうのがないと、存在が怪しいお化けと戦うことになるなあ

**Comment by Hisato-Kiara** [comment]
そうですね、ここでHowの議論をしている時間があったら私が現地に行って怪我人の一人でも診た方が意味がある気がしました。もうこの議論closeしましょう。

**Comment by daijapan** [comment]
good point! 勉強になりました
誠に有難うございました。
議論に意味はありましたね

**Comment by daijapan** [comment]
(retrospective)
good
即行動しなくてよかった
モック即作ってよかった = stripe
厳しい目で作るべきかどうか議論してよかった
bad 
東日本大震災のご経験者さんに優先度まず聞いてもいいかも
私のトーンが中央集権的だなあ。。。直そう。
next step 
当分ITより体を動かす方がバリュー出せそう
やはり現地ボランティアか。。
報道のホリジュンさんの体張って現地データを発信されているのはとても共感します
@Hisato-Kiara
